usage_report:
  reporting_enabled: false

server:
  http_listen_port: 3200

query_frontend:
  search:
    duration_slo: 5s
  trace_by_id:
    duration_slo: 5s

ingester:
  flush_all_on_shutdown: true

compactor:
  compaction:
    block_retention: 36h

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
